# https://www.redhat.com/sysadmin/introduction-tmux-linux
# Ctrl+B + I > for tpm install
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -as terminal-features ',rxvt-unicode-256color:clipboard'
setw -g mode-keys vi
set -s set-clipboard on
set -g xterm-keys on
# set -g status-bg cyan
# setw -g window-status-current-style fg=black,bg=white
set -g mouse
bind e set synchronize-panes
set-option -g detach-on-destroy off

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'aserowy/tmux.nvim'

# # navigation
# set -g @tmux-nvim-navigation true
# set -g @tmux-nvim-navigation-cycle true
# set -g @tmux-nvim-navigation-Upeybinding-left 'M-C-Left'
# set -g @tmux-nvim-navigation-Upeybinding-down 'M-C-Down'
# set -g @tmux-nvim-navigation-Upeybinding-up 'M-C-Up'
# set -g @tmux-nvim-navigation-Upeybinding-right 'M-C-Right'
#
# # resize
# set -g @tmux-nvim-resize true
# set -g @tmux-nvim-resize-step-x 1
# set -g @tmux-nvim-resize-step-y 1
# set -g @tmux-nvim-resize-Upeybinding-left 'M-C-Left'
# set -g @tmux-nvim-resize-Upeybinding-down 'M-C-Down'
# set -g @tmux-nvim-resize-Upeybinding-up 'M-C-Up'
# set -g @tmux-nvim-resize-Upeybinding-right 'M-C-Right'

# Bind tmux.nvim navigation keys
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?\.?(view|n?vim?x?)(-wrapped)?(diff)?$'"

bind-key -n 'M-C-Left' if-shell "$is_vim" 'send-keys M-C-Left' { if -F '#{pane_at_left}' '' 'select-pane -L' }
bind-key -n 'M-C-Down' if-shell "$is_vim" 'send-keys M-C-Down' { if -F '#{pane_at_bottom}' '' 'select-pane -D' }
bind-key -n 'M-C-Up' if-shell "$is_vim" 'send-keys M-C-Up' { if -F '#{pane_at_top}' '' 'select-pane -U' }
bind-key -n 'M-C-Right' if-shell "$is_vim" 'send-keys M-C-Right' { if -F '#{pane_at_right}' '' 'select-pane -R' }

bind-key -T copy-mode-vi 'M-C-Left' if -F '#{pane_at_left}' '' 'select-pane -L'
bind-key -T copy-mode-vi 'M-C-Down' if -F '#{pane_at_bottom}' '' 'select-pane -D'
bind-key -T copy-mode-vi 'M-C-Up' if -F '#{pane_at_top}' '' 'select-pane -U'
bind-key -T copy-mode-vi 'M-C-Right' if -F '#{pane_at_right}' '' 'select-pane -R'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Unbind legacy tmux navigation keys
unbind -T root 'C-h'
unbind -T root 'C-j'
unbind -T root 'C-k'
unbind -T root 'C-l'
